require("dotenv").config();

const { sequelize, connectToDatabase } = require("../config/database");
const { Category, Destination } = require("../models");

const seedDatabase = async () => {
  try {
    await connectToDatabase();

    console.log("Database connected.");

    // Masukkan kategori jika belum ada
    for (const category of categories) {
      await Category.findOrCreate({
        where: {
          name: category.name,
        },
        defaults: category,
      });
    }

    console.log("Categories seeded successfully.");

    // Ambil semua kategori dari database
    const categoryData = await Category.findAll();

    const categoryMap = {};

    categoryData.forEach((category) => {
      categoryMap[category.name] = category.id;
    });

    // Siapkan data destination
    const destinationData = destinations.map((destination) => ({
      category_id: categoryMap[destination.category],
      name: destination.name,
      description: destination.description,
      city: destination.city,
      province: destination.province,
      address: destination.address,
      latitude: destination.latitude,
      longitude: destination.longitude,
      rating: destination.rating,
      review_count: destination.review_count,
      ticket_price: destination.ticket_price,
      opening_time: destination.opening_time,
      closing_time: destination.closing_time,
      status: destination.status,
    }));

    // Cek apakah destinasi sudah ada berdasarkan nama
    for (const destination of destinationData) {
      await Destination.findOrCreate({
        where: {
          name: destination.name,
        },
        defaults: destination,
      });
    }

    console.log(`${destinationData.length} destinations processed.`);

    const totalDestinations = await Destination.count();

    console.log(`Total destinations in database: ${totalDestinations}`);

    console.log("Seeding completed successfully.");

    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error);
    process.exit(1);
  }
};

const categories = [
  {
    name: "Pantai",
    description: "Destinasi wisata pantai dan pesisir.",
  },
  {
    name: "Gunung",
    description: "Destinasi wisata pegunungan dan pendakian.",
  },
  {
  name: "Dataran Tinggi",
  description: "Destinasi wisata dataran tinggi dan kawasan pegunungan.",
  },
  {
    name: "Candi",
    description: "Destinasi wisata cagar budaya dan peninggalan sejarah.",
  },
  {
    name: "Air Terjun",
    description: "Destinasi wisata air terjun dan wisata alam.",
  },
  {
    name: "Danau",
    description: "Destinasi wisata danau dan perairan.",
  },
  {
    name: "Taman Nasional",
    description: "Kawasan konservasi dan wisata alam.",
  },
  {
    name: "Budaya",
    description: "Destinasi wisata budaya dan tradisi Indonesia.",
  },
  {
    name: "Museum",
    description: "Destinasi wisata sejarah, seni, dan edukasi.",
  },
  {
    name: "Pulau",
    description: "Destinasi wisata pulau dan kepulauan.",
  },
  {
    name: "Kota Wisata",
    description: "Kawasan perkotaan dengan daya tarik wisata.",
  },
];

const destinations = [
  // =====================
  // DI YOGYAKARTA
  // =====================
  {
    category: "Pantai",
    name: "Pantai Parangtritis",
    description: "Pantai populer di Yogyakarta dengan pemandangan Samudra Hindia.",
    city: "Bantul",
    province: "DI Yogyakarta",
    address: "Parangtritis, Kretek, Bantul",
    latitude: -8.0252,
    longitude: 110.3297,
    rating: 4.5,
    review_count: 15000,
    ticket_price: 10000,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Candi",
    name: "Candi Prambanan",
    description: "Kompleks candi Hindu terbesar di Indonesia.",
    city: "Sleman",
    province: "DI Yogyakarta",
    address: "Prambanan, Sleman",
    latitude: -7.752,
    longitude: 110.4915,
    rating: 4.8,
    review_count: 30000,
    ticket_price: 50000,
    opening_time: "06:30",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Budaya",
    name: "Keraton Yogyakarta",
    description: "Istana resmi Kesultanan Ngayogyakarta Hadiningrat.",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    address: "Jl. Rotowijayan, Kota Yogyakarta",
    latitude: -7.8053,
    longitude: 110.3642,
    rating: 4.6,
    review_count: 12000,
    ticket_price: 15000,
    opening_time: "08:00",
    closing_time: "14:00",
    status: "active",
  },
  {
    category: "Gunung",
    name: "Gunung Merapi",
    description: "Gunung berapi aktif dengan jalur wisata dan pendakian.",
    city: "Sleman",
    province: "DI Yogyakarta",
    address: "Kawasan Kaliurang, Sleman",
    latitude: -7.5407,
    longitude: 110.4461,
    rating: 4.7,
    review_count: 18000,
    ticket_price: 20000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Indrayanti",
    description: "Pantai dengan pasir putih di kawasan Gunungkidul.",
    city: "Gunungkidul",
    province: "DI Yogyakarta",
    address: "Tepus, Gunungkidul",
    latitude: -8.1507,
    longitude: 110.6125,
    rating: 4.6,
    review_count: 9000,
    ticket_price: 15000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Air Terjun",
    name: "Air Terjun Sri Gethuk",
    description: "Air terjun alami yang berada di kawasan Gunungkidul.",
    city: "Gunungkidul",
    province: "DI Yogyakarta",
    address: "Bleberan, Playen, Gunungkidul",
    latitude: -7.947,
    longitude: 110.5305,
    rating: 4.5,
    review_count: 5000,
    ticket_price: 15000,
    opening_time: "07:00",
    closing_time: "17:00",
    status: "active",
  },

  // =====================
  // JAWA TENGAH
  // =====================
  {
    category: "Candi",
    name: "Candi Borobudur",
    description: "Candi Buddha terbesar di dunia.",
    city: "Magelang",
    province: "Jawa Tengah",
    address: "Borobudur, Magelang",
    latitude: -7.6079,
    longitude: 110.2038,
    rating: 4.8,
    review_count: 45000,
    ticket_price: 50000,
    opening_time: "06:30",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Gunung",
    name: "Gunung Merbabu",
    description: "Gunung populer untuk aktivitas pendakian.",
    city: "Magelang",
    province: "Jawa Tengah",
    address: "Selo, Boyolali",
    latitude: -7.455,
    longitude: 110.438,
    rating: 4.8,
    review_count: 10000,
    ticket_price: 25000,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Kota Wisata",
    name: "Kota Lama Semarang",
    description: "Kawasan bersejarah dengan bangunan kolonial.",
    city: "Semarang",
    province: "Jawa Tengah",
    address: "Kota Lama, Semarang",
    latitude: -6.9686,
    longitude: 110.428,
    rating: 4.7,
    review_count: 16000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Dataran Tinggi",
    name: "Dieng Plateau",
    description: "Kawasan dataran tinggi dengan telaga dan wisata alam.",
    city: "Wonosobo",
    province: "Jawa Tengah",
    address: "Dieng, Wonosobo",
    latitude: -7.209,
    longitude: 109.912,
    rating: 4.7,
    review_count: 14000,
    ticket_price: 20000,
    opening_time: "06:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Air Terjun",
    name: "Curug Lawe",
    description: "Air terjun alami yang berada di kawasan Ungaran.",
    city: "Semarang",
    province: "Jawa Tengah",
    address: "Kalisidi, Ungaran",
    latitude: -7.195,
    longitude: 110.354,
    rating: 4.5,
    review_count: 3500,
    ticket_price: 10000,
    opening_time: "07:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Menganti",
    description: "Pantai dengan pemandangan tebing di Kebumen.",
    city: "Kebumen",
    province: "Jawa Tengah",
    address: "Karangduwur, Kebumen",
    latitude: -7.765,
    longitude: 109.411,
    rating: 4.7,
    review_count: 8000,
    ticket_price: 15000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },

  // =====================
  // JAWA BARAT
  // =====================
  {
    category: "Gunung",
    name: "Gunung Tangkuban Perahu",
    description: "Gunung berapi dengan kawah yang menjadi objek wisata.",
    city: "Bandung Barat",
    province: "Jawa Barat",
    address: "Lembang, Bandung Barat",
    latitude: -6.759,
    longitude: 107.6098,
    rating: 4.6,
    review_count: 22000,
    ticket_price: 30000,
    opening_time: "07:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Kota Wisata",
    name: "Kawah Putih",
    description: "Danau kawah dengan warna air khas di Ciwidey.",
    city: "Bandung",
    province: "Jawa Barat",
    address: "Ciwidey, Bandung",
    latitude: -7.166,
    longitude: 107.402,
    rating: 4.7,
    review_count: 25000,
    ticket_price: 30000,
    opening_time: "07:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Taman Nasional",
    name: "Taman Nasional Gunung Gede Pangrango",
    description: "Kawasan konservasi dengan jalur pendakian.",
    city: "Cianjur",
    province: "Jawa Barat",
    address: "Cibodas, Cianjur",
    latitude: -6.778,
    longitude: 106.983,
    rating: 4.8,
    review_count: 11000,
    ticket_price: 30000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Pangandaran",
    description: "Pantai terkenal di pesisir selatan Jawa Barat.",
    city: "Pangandaran",
    province: "Jawa Barat",
    address: "Pangandaran",
    latitude: -7.684,
    longitude: 108.65,
    rating: 4.6,
    review_count: 28000,
    ticket_price: 15000,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Air Terjun",
    name: "Curug Cimahi",
    description: "Air terjun populer di kawasan Bandung Barat.",
    city: "Bandung Barat",
    province: "Jawa Barat",
    address: "Cisarua, Bandung Barat",
    latitude: -6.788,
    longitude: 107.562,
    rating: 4.5,
    review_count: 7000,
    ticket_price: 20000,
    opening_time: "08:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Budaya",
    name: "Saung Angklung Udjo",
    description: "Pusat pertunjukan dan pelestarian budaya angklung.",
    city: "Bandung",
    province: "Jawa Barat",
    address: "Jl. Padasuka, Bandung",
    latitude: -6.899,
    longitude: 107.65,
    rating: 4.7,
    review_count: 12000,
    ticket_price: 85000,
    opening_time: "09:00",
    closing_time: "17:00",
    status: "active",
  },

  // =====================
  // JAWA TIMUR
  // =====================
  {
    category: "Gunung",
    name: "Gunung Bromo",
    description: "Gunung berapi aktif dengan pemandangan matahari terbit.",
    city: "Probolinggo",
    province: "Jawa Timur",
    address: "Bromo, Probolinggo",
    latitude: -7.942,
    longitude: 112.953,
    rating: 4.9,
    review_count: 50000,
    ticket_price: 30000,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Kota Wisata",
    name: "Kota Batu",
    description: "Kota wisata dengan berbagai taman hiburan dan wisata alam.",
    city: "Batu",
    province: "Jawa Timur",
    address: "Kota Batu",
    latitude: -7.867,
    longitude: 112.523,
    rating: 4.7,
    review_count: 20000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Air Terjun",
    name: "Air Terjun Tumpak Sewu",
    description: "Air terjun besar dengan panorama tebing hijau.",
    city: "Lumajang",
    province: "Jawa Timur",
    address: "Pronojiwo, Lumajang",
    latitude: -8.231,
    longitude: 112.919,
    rating: 4.8,
    review_count: 18000,
    ticket_price: 20000,
    opening_time: "07:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Taman Nasional",
    name: "Taman Nasional Baluran",
    description: "Kawasan konservasi dengan savana luas.",
    city: "Situbondo",
    province: "Jawa Timur",
    address: "Banyuputih, Situbondo",
    latitude: -7.843,
    longitude: 114.387,
    rating: 4.6,
    review_count: 9000,
    ticket_price: 25000,
    opening_time: "07:00",
    closing_time: "16:00",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Papuma",
    description: "Pantai dengan batu karang besar di pesisir Jember.",
    city: "Jember",
    province: "Jawa Timur",
    address: "Lojejer, Jember",
    latitude: -8.468,
    longitude: 113.567,
    rating: 4.6,
    review_count: 8500,
    ticket_price: 20000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },

  // =====================
  // BALI
  // =====================
  {
    category: "Pantai",
    name: "Pantai Kuta",
    description: "Pantai terkenal di Bali dengan ombak untuk berselancar.",
    city: "Badung",
    province: "Bali",
    address: "Kuta, Badung",
    latitude: -8.717,
    longitude: 115.168,
    rating: 4.6,
    review_count: 60000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Budaya",
    name: "Pura Tanah Lot",
    description: "Pura yang berada di atas batu karang di tepi laut.",
    city: "Tabanan",
    province: "Bali",
    address: "Beraban, Tabanan",
    latitude: -8.621,
    longitude: 115.087,
    rating: 4.7,
    review_count: 35000,
    ticket_price: 60000,
    opening_time: "07:00",
    closing_time: "19:00",
    status: "active",
  },
  {
    category: "Danau",
    name: "Danau Beratan",
    description: "Danau dengan panorama pegunungan dan Pura Ulun Danu.",
    city: "Tabanan",
    province: "Bali",
    address: "Bedugul, Tabanan",
    latitude: -8.275,
    longitude: 115.166,
    rating: 4.7,
    review_count: 20000,
    ticket_price: 50000,
    opening_time: "07:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Gunung",
    name: "Gunung Batur",
    description: "Gunung populer untuk trekking melihat matahari terbit.",
    city: "Bangli",
    province: "Bali",
    address: "Kintamani, Bangli",
    latitude: -8.242,
    longitude: 115.375,
    rating: 4.8,
    review_count: 15000,
    ticket_price: 100000,
    opening_time: "02:00",
    closing_time: "12:00",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Pandawa",
    description: "Pantai pasir putih di bagian selatan Bali.",
    city: "Badung",
    province: "Bali",
    address: "Kutuh, Badung",
    latitude: -8.844,
    longitude: 115.188,
    rating: 4.7,
    review_count: 22000,
    ticket_price: 15000,
    opening_time: "07:00",
    closing_time: "19:00",
    status: "active",
  },
  // =====================
  // NUSA TENGGARA BARAT
  // =====================
  {
    category: "Pulau",
    name: "Gili Trawangan",
    description: "Pulau wisata populer dengan pantai dan aktivitas snorkeling.",
    city: "Lombok Utara",
    province: "Nusa Tenggara Barat",
    address: "Gili Trawangan, Lombok Utara",
    latitude: -8.351,
    longitude: 116.039,
    rating: 4.7,
    review_count: 25000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Tanjung Aan",
    description: "Pantai berpasir putih dengan panorama perbukitan.",
    city: "Lombok Tengah",
    province: "Nusa Tenggara Barat",
    address: "Kuta, Pujut, Lombok Tengah",
    latitude: -8.879,
    longitude: 116.295,
    rating: 4.7,
    review_count: 8500,
    ticket_price: 10000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Gunung",
    name: "Gunung Rinjani",
    description: "Gunung berapi dengan jalur pendakian dan Danau Segara Anak.",
    city: "Lombok Timur",
    province: "Nusa Tenggara Barat",
    address: "Sembalun, Lombok Timur",
    latitude: -8.411,
    longitude: 116.458,
    rating: 4.9,
    review_count: 30000,
    ticket_price: 150000,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },

  // =====================
  // NUSA TENGGARA TIMUR
  // =====================
  {
    category: "Pulau",
    name: "Pulau Komodo",
    description: "Pulau habitat asli komodo dan bagian dari kawasan konservasi.",
    city: "Manggarai Barat",
    province: "Nusa Tenggara Timur",
    address: "Taman Nasional Komodo, Labuan Bajo",
    latitude: -8.585,
    longitude: 119.489,
    rating: 4.9,
    review_count: 40000,
    ticket_price: 150000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Pink",
    description: "Pantai dengan pasir berwarna merah muda di Pulau Komodo.",
    city: "Manggarai Barat",
    province: "Nusa Tenggara Timur",
    address: "Pulau Komodo, Manggarai Barat",
    latitude: -8.605,
    longitude: 119.525,
    rating: 4.8,
    review_count: 12000,
    ticket_price: 50000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Danau",
    name: "Danau Kelimutu",
    description: "Danau kawah terkenal dengan tiga warna air yang dapat berubah.",
    city: "Ende",
    province: "Nusa Tenggara Timur",
    address: "Moni, Ende",
    latitude: -8.77,
    longitude: 121.826,
    rating: 4.8,
    review_count: 11000,
    ticket_price: 150000,
    opening_time: "04:00",
    closing_time: "18:00",
    status: "active",
  },

  // =====================
  // SUMATERA UTARA
  // =====================
  {
    category: "Danau",
    name: "Danau Toba",
    description: "Danau vulkanik terbesar di Indonesia dengan Pulau Samosir.",
    city: "Toba",
    province: "Sumatera Utara",
    address: "Kawasan Danau Toba",
    latitude: 2.684,
    longitude: 98.875,
    rating: 4.8,
    review_count: 45000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Taman Nasional",
    name: "Taman Nasional Gunung Leuser",
    description: "Kawasan konservasi yang menjadi habitat berbagai satwa.",
    city: "Langkat",
    province: "Sumatera Utara",
    address: "Bukit Lawang, Langkat",
    latitude: 3.548,
    longitude: 98.12,
    rating: 4.7,
    review_count: 9000,
    ticket_price: 150000,
    opening_time: "07:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Air Terjun",
    name: "Air Terjun Sipiso-piso",
    description: "Air terjun tinggi dengan panorama Danau Toba.",
    city: "Karo",
    province: "Sumatera Utara",
    address: "Merek, Karo",
    latitude: 2.918,
    longitude: 98.5,
    rating: 4.7,
    review_count: 7500,
    ticket_price: 10000,
    opening_time: "07:00",
    closing_time: "18:00",
    status: "active",
  },

  // =====================
  // SUMATERA BARAT
  // =====================
  {
    category: "Danau",
    name: "Danau Maninjau",
    description: "Danau vulkanik dengan pemandangan perbukitan.",
    city: "Agam",
    province: "Sumatera Barat",
    address: "Tanjung Raya, Agam",
    latitude: -0.302,
    longitude: 100.174,
    rating: 4.7,
    review_count: 8500,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Budaya",
    name: "Istano Basa Pagaruyung",
    description: "Bangunan adat Minangkabau yang menjadi ikon budaya Sumatera Barat.",
    city: "Tanah Datar",
    province: "Sumatera Barat",
    address: "Tanjung Emas, Tanah Datar",
    latitude: -0.471,
    longitude: 100.62,
    rating: 4.7,
    review_count: 13000,
    ticket_price: 20000,
    opening_time: "08:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Air Terjun",
    name: "Lembah Anai",
    description: "Kawasan air terjun yang berada di jalur Padang menuju Bukittinggi.",
    city: "Tanah Datar",
    province: "Sumatera Barat",
    address: "Lembah Anai, Tanah Datar",
    latitude: -0.466,
    longitude: 100.467,
    rating: 4.6,
    review_count: 9000,
    ticket_price: 10000,
    opening_time: "07:00",
    closing_time: "18:00",
    status: "active",
  },

  // =====================
  // JAKARTA
  // =====================
  {
    category: "Museum",
    name: "Museum Nasional Indonesia",
    description: "Museum yang menyimpan berbagai koleksi sejarah dan budaya Indonesia.",
    city: "Jakarta Pusat",
    province: "DKI Jakarta",
    address: "Jl. Medan Merdeka Barat, Jakarta Pusat",
    latitude: -6.176,
    longitude: 106.821,
    rating: 4.7,
    review_count: 18000,
    ticket_price: 25000,
    opening_time: "08:00",
    closing_time: "16:00",
    status: "active",
  },
  {
    category: "Pulau",
    name: "Kepulauan Seribu",
    description: "Kawasan kepulauan dengan berbagai pulau wisata di utara Jakarta.",
    city: "Kepulauan Seribu",
    province: "DKI Jakarta",
    address: "Kepulauan Seribu",
    latitude: -5.75,
    longitude: 106.6,
    rating: 4.6,
    review_count: 15000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Kota Wisata",
    name: "Kota Tua Jakarta",
    description: "Kawasan bersejarah dengan bangunan peninggalan kolonial.",
    city: "Jakarta Barat",
    province: "DKI Jakarta",
    address: "Kota Tua, Jakarta Barat",
    latitude: -6.135,
    longitude: 106.814,
    rating: 4.6,
    review_count: 30000,
    ticket_price: 0,
    opening_time: "08:00",
    closing_time: "22:00",
    status: "active",
  },

  // =====================
  // SULAWESI SELATAN
  // =====================
  {
    category: "Budaya",
    name: "Tana Toraja",
    description: "Kawasan budaya dengan rumah adat Tongkonan dan tradisi khas.",
    city: "Tana Toraja",
    province: "Sulawesi Selatan",
    address: "Tana Toraja",
    latitude: -3.075,
    longitude: 119.742,
    rating: 4.8,
    review_count: 18000,
    ticket_price: 0,
    opening_time: "08:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Pantai",
    name: "Pantai Losari",
    description: "Kawasan pantai terkenal di pusat Kota Makassar.",
    city: "Makassar",
    province: "Sulawesi Selatan",
    address: "Jl. Penghibur, Makassar",
    latitude: -5.141,
    longitude: 119.409,
    rating: 4.5,
    review_count: 25000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },
  {
    category: "Taman Nasional",
    name: "Taman Nasional Bantimurung Bulusaraung",
    description: "Kawasan konservasi dengan air terjun dan keanekaragaman hayati.",
    city: "Maros",
    province: "Sulawesi Selatan",
    address: "Bantimurung, Maros",
    latitude: -5.015,
    longitude: 119.681,
    rating: 4.7,
    review_count: 7000,
    ticket_price: 30000,
    opening_time: "07:00",
    closing_time: "17:00",
    status: "active",
  },

  // =====================
  // SULAWESI UTARA
  // =====================
  {
    category: "Taman Nasional",
    name: "Taman Nasional Bunaken",
    description: "Taman laut terkenal dengan keindahan terumbu karang.",
    city: "Manado",
    province: "Sulawesi Utara",
    address: "Bunaken, Manado",
    latitude: 1.617,
    longitude: 124.755,
    rating: 4.9,
    review_count: 22000,
    ticket_price: 50000,
    opening_time: "07:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Danau",
    name: "Danau Tondano",
    description: "Danau luas dengan panorama pegunungan di Sulawesi Utara.",
    city: "Minahasa",
    province: "Sulawesi Utara",
    address: "Tondano, Minahasa",
    latitude: 1.292,
    longitude: 124.913,
    rating: 4.6,
    review_count: 5000,
    ticket_price: 0,
    opening_time: "00:00",
    closing_time: "23:59",
    status: "active",
  },

  // =====================
  // PAPUA
  // =====================
  {
    category: "Pulau",
    name: "Raja Ampat",
    description: "Kepulauan dengan keanekaragaman hayati laut dan panorama karst.",
    city: "Raja Ampat",
    province: "Papua Barat Daya",
    address: "Raja Ampat",
    latitude: -0.234,
    longitude: 130.517,
    rating: 5.0,
    review_count: 35000,
    ticket_price: 100000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
  {
    category: "Budaya",
    name: "Lembah Baliem",
    description: "Lembah pegunungan dengan kekayaan budaya masyarakat Papua.",
    city: "Jayawijaya",
    province: "Papua Pegunungan",
    address: "Wamena, Jayawijaya",
    latitude: -4.084,
    longitude: 138.954,
    rating: 4.7,
    review_count: 6000,
    ticket_price: 50000,
    opening_time: "08:00",
    closing_time: "17:00",
    status: "active",
  },
  {
    category: "Danau",
    name: "Danau Sentani",
    description: "Danau luas yang berada di sekitar wilayah Jayapura.",
    city: "Jayapura",
    province: "Papua",
    address: "Sentani, Jayapura",
    latitude: -2.611,
    longitude: 140.517,
    rating: 4.7,
    review_count: 8000,
    ticket_price: 20000,
    opening_time: "06:00",
    closing_time: "18:00",
    status: "active",
  },
];

seedDatabase();